version: "3"

services:
  server:
    build:
      context: .
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydb
      ENV: production
      PORT: 3000
      JWT_SECRET: my_super_secret123@!
    ports:
      - "80:3000"
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
